### ISSUE TITLE
TypeError Error in Version 0.8.0

### ISSUE THREAD

**Issue by BjBe82** [eclipse/sprotty-layout#12]
We upgraded to the latest version of this project to test if the port layout is working. But if port layout is required, we get the following exception:

```
11:19:01 sprotty MBSEDiagramModelSource: TypeError: index.getParent is not a function TypeError: index.getParent is not a function
    at ElkLayoutEngine../node_modules/sprotty-elk/lib/elk-layout.js.ElkLayoutEngine.transformToElk (e:\VSWorkspace\sprotty_showroom\node_modules\sprotty-elk\src\elk-layout.ts:116:42)
    at e:\VSWorkspace\sprotty_showroom\node_modules\sprotty-elk\src\elk-layout.ts:77:40
    at Array.map (<anonymous>)
    at ElkLayoutEngine../node_modules/sprotty-elk/lib/elk-layout.js.ElkLayoutEngine.transformToElk (e:\VSWorkspace\sprotty_showroom\node_modules\sprotty-elk\src\elk-layout.ts:77:26)
    at ElkLayoutEngine../node_modules/sprotty-elk/lib/elk-layout.js.ElkLayoutEngine.layout (e:\VSWorkspace\sprotty_showroom\node_modules\sprotty-elk\src\elk-layout.ts:56:31)
    at MBSEDiagramModelSource.<anonymous> (e:\VSWorkspace\sprotty_showroom\node_modules\sprotty\src\model-source\local-model-source.ts:148:56)
    at step (http://localhost:3000/js/app_bundle.js:46288:23)
    at Object.next (http://localhost:3000/js/app_bundle.js:46269:53)
    at http://localhost:3000/js/app_bundle.js:46263:71
    at new Promise (<anonymous>)
```

The package.json dependencies look like this:

  ```
"dependencies": {
    "@fortawesome/fontawesome": "^1.1.8",
    "@fortawesome/fontawesome-free-brands": "^5.0.13",
    "@fortawesome/fontawesome-free-solid": "^5.0.13",
    "@types/bootstrap-select": "^1.11.1",
    "@types/bootstrap-toggle": "^2.2.1",
    "autocompleter": "6.0.1",
    "bootstrap": "^4.4.1",
    "bootstrap-select": "^1.13.12",
    "bootstrap-toggle": "^2.2.2",
    "devbridge-autocomplete": "1.4.10",
    "elkjs": "latest",
    "file-saver": "2.0.2",
    "guid-typescript": "^1.0.9",
    "inversify": "5.0.1",
    "jquery": "^3.4.1",
    "node-sass": "^4.13.1",
    "nodemon": "^2.0.2",
    "snabbdom": "0.7.4",
    "snabbdom-jsx": "0.4.2",
    "snabbdom-virtualize": "0.7.0",
    "sprotty": "0.8.0",
    "sprotty-elk": "0.8.0"
  }
```

**Comment by BjBe82** [comment]
Just to capture the Problem.
```
LocalModelSource::submitModel(...)
....
            const index = this.computedBoundsApplicator.apply(this.currentRoot, computedBounds);
            await this.doSubmitModel(newRoot, true, cause, index);
....
```
creates a SModelIndex which is forwarded to
```
LocalModelSource:: doSubmitModel (...)
....
            const layoutResult = this.layoutEngine.layout(newRoot, index);
....
```
Because of this the layout engine (sprotty-elk) receives a normal SModelIndex but needs a SModelIndexWithParent for ports.
